[package]
name = "texted2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntex = { version = "1.0", features = ["tokio"] }
ntex-files = "0.4.1"
serde = "1"
ramhorns = "0.14.0"
lazy_static = { version = "1.4.0", features = [] }
regex = "1.10"
markdown = "1.0.0-alpha.16"
