[package]
name = "texted2"
version = "0.1.2"
edition = "2021"
authors = ["Thiago Massari Guedes"]
license = "Apache-2.0"
homepage = "https://gitlab.com/thiagomg/texted2"
repository = "https://gitlab.com/thiagomg/texted2"
description = "A markdown blog platform that lets you in control of your data"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntex = { version = "1.0", features = ["tokio"] }
ntex-files = "0.4.1"
serde = "1"
ramhorns = "0.14.0"
lazy_static = { version = "1.4.0", features = [] }
regex = "1.10"
markdown = "1.0.0-alpha.16"
chrono = "0.4.34"
toml = "0.8.10"
uuid = { version = "1", features = ["v4", "fast-rng"] }
whoami = "1"
clap = { version = "4.5", features = ["derive"] }
dirs = "5.0.1"
