[package]
name = "texted"
version = "1.0.0"
edition = "2021"
authors = ["Thiago Massari Guedes"]
license = "Apache-2.0"
homepage = "https://gitlab.com/thiagomg/texted"
repository = "https://gitlab.com/thiagomg/texted"
description = "A markdown blog platform that lets you in control of your data"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
flate2 = "1.0.30"
tar = "0.4.40"


[dependencies]
ntex = { version = "2.3.0", features = ["tokio"] }
ntex-files = "2.0.0"
serde = { version = "1.0.208", features = ["derive"] }
ramhorns = "1.0.0"
lazy_static = { version = "1.5.0", features = [] }
regex = "1.10.6"
markdown = "1.0.0-alpha.20"
chrono = { version = "0.4.38", features = ["serde"] }
toml = "0.8.19"
uuid = { version = "1.10.0", features = ["v4", "fast-rng"] }
whoami = "1.5.1"
clap = { version = "4.5.16", features = ["derive", "string"] }
dirs = "5.0.1"
serde_urlencoded = "0.7.1"
anyhow = "1.0.82"
spdlog-rs = "0.3.13"
flate2 = "1.0.32"
tar = "0.4.41"
unidecode = "0.3.0"
serde_json = "1.0.127"
tokio = "1.39.3"
quick-xml = "0.36.1"
