[personal]
activity_start_year = 2000

# For the file locations, If you want it to be relative to the executable directory
# use ${exe_dir}/location
[paths]
template_dir = "res/template"
public_dir = "res/public"
posts_dir = "posts"

[posts]
post_file_name = "index.md"

[server]
address = "0.0.0.0"
port = 8001
